### ISSUE TITLE
CSV File Download in proper format?

### ISSUE THREAD

**Issue by joesan** [mlangc/ml-weather-basel-blog#1]
You have a great write up on the subject. I'm looking as well into using smile for some linear regression and as an inspiration, I was following your code samples. I however have a question. I tried to download the CSV file from the Meteoblue website you mentioned and here is a sample below.

```
LAT |   |   |   |   | 47.5584 | 47.5584 | 47.5584
-- | -- | -- | -- | -- | -- | -- | --
LON |   |   |   |   | 7.57327 | 7.57327 | 7.57327
ASL |   |   |   |   | 279 | 279 | 279
CITY |   |   |   |   | Basel | Basel | Basel
DOMAIN |   |   |   |   | NEMS4 | NEMS4 | NEMS4
LEVEL |   |   |   |   | 2 m above gnd | sfc | sfc
NAME |   |   |   |   | Temperature | Total Precipitation (high resolution) | Total Cloud Cover
UNIT |   |   |   |   | °C | mm | %
AGGREGATION |   |   |   |   | daily mean | daily sum | daily mean
UTC_OFFSET |   |   |   |   | 1 | 1 | 1
  |   |   |   |   |   |   |  
Year | Month | Day | Hour | Minute | Temperature daily mean [2 m above gnd] | Total Precipitation (high resolution) daily sum [sfc] | Total Cloud Cover daily mean [sfc]
2019 | 2 | 19 | 0 | 0 | 8.44 | 0 | 27.41
2019 | 2 | 20 | 0 | 0 | 9.39 | 0 | 31.21
2019 | 2 | 21 | 0 | 0 | 10.09 | 0 | 1.73
2019 | 2 | 22 | 0 | 0 | 9.48 | 0 | 52.18
2019 | 2 | 23 | 0 | 0 | 7.04 | 0 | 17.38
2019 | 2 | 24 | 0 | 0 | 5.31 | 0 | 0.41
2019 | 2 | 25 | 0 | 0 | 7.12 | 0 | 0.81
2019 | 2 | 26 | 0 | 0 | 9.47 | 0 | 2.71


```

Where in your code are you parsing this CSV file? To me it does not look like a proper CSV file. Looking at the header. Are you doing any pre processing of the CSV file as soon as you download them? Can you share a sample of the CSV file that you have?

The idea for me is to try out linear regression using smile in an operational fashion - meaning that I want to run this project as an integrated end-to-end machine learning using CI / CD, automated training etc., but first I need to figure out how to read the CSV data properly. Looking at the data that I downloaded, looks like I have to do some manual preprocessing and I want to somehow avoid that. So please let me know what CSV format you have!

**Comment by mlangc** [comment]
The code that does the parsing is here: https://github.com/mlangc/ml-weather-basel-blog/blob/master/src/main/scala/com/github/mlangc/wetterfrosch/HistoryExportParser.scala

Maybe the column separator depends on the locale of your browser? Did you use the link that is provided here: https://github.com/mlangc/ml-weather-basel-blog?

Also note, that you have to manually throw away the header that looks like this:
```
LAT;;;;;47.5584;47.5584;47.5584;47.5584
LON;;;;;7.57327;7.57327;7.57327;7.57327
ASL;;;;;279.000;279.000;279.000;279.000
CITY;;;;;Basel;Basel;Basel;Basel
DOMAIN;;;;;NEMS4;NEMS4;NEMS4;NEMS4
LEVEL;;;;;2 m above gnd;sfc;10 m above gnd;10 m above gnd
NAME;;;;;Temperature;Total Precipitation (high resolution);Wind Speed;Wind Direction
UNIT;;;;;°C;mm;km/h;°
AGGREGATION;;;;;;;;
UTC_OFFSET;;;;;1;1;1;1
```

**Comment by joesan** [comment]
Yes, I used the link that you provided to download the data. I wanted to avoid doing anything manually. I was wondering if they had an API that I can integrate in my workflow. So every time I run the ML pipeline, I download the data from meteoblue, parse it, remove the header and use it for training and testing. But nevertheless, I found out that they charge for using the API. 

So now I will have to remove the header manually and provide it to the application.

**Comment by mlangc** [comment]
I guess this is something you might want to discuss with meteoblue... maybe they have an API, I didn't look, since I don't need it.

I will update the README to clarify that the preamble of the file has to be removed and close this ticket. Thanks for your feedback and good luck!

**Comment by mlangc** [comment]
It seems that meteoblue has changed some columns in the data. To avoid further headaches, I've included the CSVs in the proper format directly in the git repo. I've also adapted the parser a bit, so that it ignores anything until the CSV header.
